### PR TITLE
Machinery to serve Pluggable Components.

### LINKED ISSUE #8: Split SDK code and example code
Ideally we want SDK code to compile on its own and code samples/examples to be separated projects built independently from the SDK. One option is to move example code to a separate folder in the root directory of the project, as it is done in Dapr Java SDK.

### LINKED ISSUE #10: Java API for Pluggable components can't run on MacOS
## Describe the feature

While trying to run the pluggable components Java SDK on MacOS users receive the following error:

```
INFO: Taking unix socket domain path from env. var. DAPR_COMPONENT_SOCKET_PATH
Sep 22, 2022 4:35:54 PM org.example.StateStoreComponentServer main
INFO: Starting a StateStoreComponentServer...
Sep 22, 2022 4:35:54 PM org.example.StateStoreComponentServer buildUnixSocketServer
INFO: Configuring server to listen to unix socket domain on file /tmp/sharedUDS/javaMemstore.socket
Exception in thread "main" java.lang.UnsatisfiedLinkError: failed to load the required native library
    at io.netty.channel.epoll.Epoll.ensureAvailability(Epoll.java:81)
    at io.netty.channel.epoll.EpollEventLoop.<clinit>(EpollEventLoop.java:54)
    at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:186)
    at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:37)
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:60)
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:49)
    at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
    at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:114)
    at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:101)
    at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:78)
    at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:54)
    at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:47)
    at org.example.StateStoreComponentServer.buildUnixSocketServer(StateStoreComponentServer.java:86)
    at org.example.StateStoreComponentServer.main(StateStoreComponentServer.java:63)
Caused by: java.lang.ExceptionInInitializerError
    at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:40)
    ... 14 more
Caused by: java.lang.IllegalStateException: Only supported on Linux
    at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:317)
    at io.netty.channel.epoll.Native.<clinit>(Native.java:85)
    ... 15 more

```

This might be a problem with Netty support for UDS but regardless it needs to be addressed. FWIW, this might be the wrong repo for this issue.

### PR DESCRIPTION
**Pull request by tmacam**
# Description

* Defines a pluggable component as a container.
* Defines a server for collection of pluggable components.
* Defines common State Store Exceptions that wrapping gRPC Status in the format expected by Dapr. This allows for error reporting from the pluggable component to Dapr and its clients.
* Adds Netty Unix Domain Sockets dependencies for both Linux and macOS, for both AMD64 and ARM64. Closes #10.
* Splits example code into another maven project. Closes #8.
* Adds a sample In-Memory State Store sample application.

## Issue reference

* Closes #8
* Closes #10
* Opens #21

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

File: components-java-sdk-examples/src/main/java/io/dapr/examples/statestore/InMemoryStateStore.java [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+  @Override
+  public Mono<Void> init(Map<String, String> properties) {
+    // log.info("Initializing InMemoryState Store."); // I was born ready, babe
+    return Mono.empty();
+  }
+
+  //  @Override
+  //  public Mono<List<String>> getFeatures() {
+  //    return Mono.just(Collections.emptyList());
+  //  }
```
Comment (tmacam) [inline components-java-sdk-examples/src/main/java/io/dapr/examples/statestore/InMemoryStateStore.java:41]: This can be removed. I thought about advertising etag support but I don't have it done properly,

File: components-java-sdk/src/main/java/io/dapr/components/server/Constants.java [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package io.dapr.components.server;
+
+/**
+ * Constant definitions.
+ */
```
Comment (tmacam) [inline components-java-sdk/src/main/java/io/dapr/components/server/Constants.java:18]: Unapologetically copied from https://github.com/dapr-sandbox/components-dotnet-sdk/blob/main/src/Dapr.PluggableComponents/Constants.cs ;)

File: components-java-sdk/src/main/java/io/dapr/components/server/PluggableComponent.java [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+ * <p>A PluggableComponent instance by itself is not capable of receiving and handling requests:
+ * you need to add it to a {@link PluggableComponentServer}.</p>
+ */
+public final class PluggableComponent {
+  private final String name;
+
+  private final List<BindableService> exposedServices = new ArrayList<>();
+
+  // A given component API (state store, pubusb, binding etc) can be registered only once.
+  private boolean alreadyAddedStaStore = false;
```
Comment (tmacam) [inline components-java-sdk/src/main/java/io/dapr/components/server/PluggableComponent.java:50]: Typo: "StaStore"

File: components-java-sdk-examples/src/main/java/io/dapr/examples/statestore/InMemoryStateStore.java [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+import java.util.HashMap;
+import java.util.Map;
+
+public class InMemoryStateStore implements StateStore {
+
+  private final Map<String, GetResponse> entries = new HashMap<>();
+
+  @Override
+  public Mono<Void> init(Map<String, String> properties) {
+    // log.info("Initializing InMemoryState Store."); // I was born ready, babe
```
Comment (philliphoff) [inline components-java-sdk-examples/src/main/java/io/dapr/examples/statestore/InMemoryStateStore.java:34]: Nit: remove the commented-out line altogether?

File: components-java-sdk/src/main/java/io/dapr/components/server/PluggableComponentServer.java [hunk 5]
```diff
@@ -0,0 +1,248 @@
...
+      log.info("Started server for " + componentName);
+    }
+
+    Runtime.getRuntime().addShutdownHook(new Thread(() -> {
+      // Use stderr here since the logger may have been reset by its JVM shutdown hook.
+      System.err.println("*** shutting down gRPC server since JVM is shutting down");
+      servers.forEach((componentName, server) -> {
+        try {
+          System.err.println("    *** shutting doing server instance " + server.toString());
+          server.shutdown().awaitTermination(30, TimeUnit.SECONDS);
```
Comment (philliphoff) [inline components-java-sdk/src/main/java/io/dapr/components/server/PluggableComponentServer.java:223]: Questions as one not familiar with the Java gRPC library: would the servers already be shutting down at this point, and that's just being awaited here, or is this initiating the shutdown?  Is this wait sequential?  Would it add up in the case of multiple servers (vs. the parallel await in the `blockUntilShutdown()` method.

File: components-java-sdk/src/main/java/io/dapr/components/server/PluggableComponentServer.java [hunk 6]
```diff
@@ -0,0 +1,248 @@
...
+    if (exposedServices.isEmpty()) {
+      logFatalAndAbort("Pluggable component " + componentName
+          + " is not exposing any service or Dapr API. Aborting.");
+    }
+
+    // Unix Domain Socket setup
+    final var componentUdsPath = buildPathForComponentUnixDomainSocket(componentName);
+    log.info("Configuring server to listen to unix socket domain on file " + componentUdsPath.toAbsolutePath());
+    // If file exists, remove it.
+    final File componentUdsFile = componentUdsPath.toFile();
```
Comment (philliphoff) [inline components-java-sdk/src/main/java/io/dapr/components/server/PluggableComponentServer.java:118]: Does Java need to update the permissions of the UDS file post-creation like in .NET due to permissions differences between the sidecar and component?

File: components-java-sdk-examples/src/main/java/io/dapr/examples/InMemoryStateStorePluggableComponentServer.java [hunk 7]
```diff
@@ -0,0 +1,39 @@
...
+   *
+   * @param args Command line arguments that we ignore.
+   * @throws IOException if we face errors starting this server.
+   */
+  public static void main(String[] args) throws IOException {
+
+    final PluggableComponentServer server = new PluggableComponentServer();
+    server.registerComponent(PluggableComponent
+            .withName("my-in-memory-state-store")
+            .withStateStore(new InMemoryStateStore())
```
Comment (philliphoff) [inline components-java-sdk-examples/src/main/java/io/dapr/examples/InMemoryStateStorePluggableComponentServer.java:35]: Components are strictly singletons across all component instances?  (At least, for this iteration?)

Comment (tmacam) [reply components-java-sdk-examples/src/main/java/io/dapr/examples/InMemoryStateStorePluggableComponentServer.java:35]: I am not enforcing that. There can be as many `InMemoryStateStore` instances across different `PluggableComponent` as desired. 

Now, a single pluggable component can only host a single StateStore. Not sure if that is what you meant.

File: components-java-sdk/src/main/java/io/dapr/components/server/PluggableComponentServer.java (hunk 6 above)
Comment (tmacam) [reply components-java-sdk/src/main/java/io/dapr/components/server/PluggableComponentServer.java:118]: Yes, it it need - umask on macos by default is pretty lax! Got catch!

File: components-java-sdk/src/main/java/io/dapr/components/server/PluggableComponentServer.java (hunk 5 above)
Comment (tmacam) [reply components-java-sdk/src/main/java/io/dapr/components/server/PluggableComponentServer.java:224]: > Questions as one not familiar with the Java gRPC library: 
> would the servers already be shutting down at this point, and that's just being awaited here, or is this initiating the shutdown?

This code sequence initialize a "clean" shutdown if the server process receives a signal to terminal (Say, a Ctrl-C/ sig KILL).

>  Is this wait sequential? Would it add up in the case of multiple servers (vs. the parallel await in the `blockUntilShutdown()` method.

 Yes, it is sequential. I can make it parallel.

File: components-java-sdk/src/main/java/io/dapr/components/server/PluggableComponentServer.java (hunk 6 above)
Comment (tmacam) [reply components-java-sdk/src/main/java/io/dapr/components/server/PluggableComponentServer.java:118]: This is now addressed on `fixUnixDomainSocketFilePermissions()`, called after the `server.start()`, as the UDS is only created then: here we are just doing sanity checks and cleanups.

File: components-java-sdk/pom.xml [hunk 8]
```diff
@@ -27,11 +27,38 @@
...
             <artifactId>reactor-core</artifactId>
             <version>3.3.11.RELEASE</version>
         </dependency>
-    </dependencies>
 
+        <!-- Netty's Unix Domain Socket support for Linux and Mac, for both AMD64 and ARM64 -->
+        <dependency>
+            <groupId>io.netty</groupId>
+            <artifactId>netty-transport-native-kqueue</artifactId>
+            <version>4.1.79.Final</version>
```
Comment (tmacam) [inline components-java-sdk/pom.xml:42]: This should be a variable to avoid repetition and to ensure this is kept in sync with the remaining Netty components.

Comment (tmacam) [reply components-java-sdk/pom.xml]: Fixed on 0615d0bf3f228b98728feb7dfae39f978181332d

File: components-java-sdk-examples/src/main/java/io/dapr/examples/InMemoryStateStorePluggableComponentServer.java (hunk 7 above)
Comment (philliphoff) [reply components-java-sdk-examples/src/main/java/io/dapr/examples/InMemoryStateStorePluggableComponentServer.java:35]: As we discussed, I think that's fine. We'll see if there's customer feedback for more multiplexing options.

**Review by philliphoff — APPROVED** [review]
